export {default as BlogWriter} from '__board__/pages/BlogWriter'
export {default as BlogList} from '__board__/pages/BlogList'
export {default as BlogDetailsStandard} from '__board__/pages/BlogDetailsStandard'
export {default as BlogUpdate} from '__board__/pages/BlogUpdate'
export {default as CommentUpdate} from '__board__/pages/CommentUpdate'

export {default as BlogPostDetail}  from '__board__/modules/BlogPostDetail'
export {default as BlogPostList} from '__board__/modules/BlogPostList'
export {default as BlogPostWriter} from '__board__/modules/BlogPostWriter'
export {default as BlogPostUpdate} from '__board__/modules/BlogPostUpdate'
export {default as BlogComment} from '__board__/modules/BlogComment'
export {default as BlogSearch} from '__board__/modules/BlogSearch'
export {default as BlogCommentUpdate} from '__board__/modules/BlogCommentUpdate'
export {default as Pagination} from '__board__/modules/Pagination'
export {default as Paginations} from '__board__/modules/Paginations'

export {default as BlogApp} from '__board__/modules/BlogApp'
export {default as Posts} from '__board__/modules/Posts'
