export { default as Checkout } from '__payment__/pages/Checkout'
export { default as MyAccount } from '__payment__/pages/MyAccount'
export { default as MyAccountDetail } from '__payment__/pages/MyAccountDetail'
export { default as SuccessPage } from '__payment__/pages/SuccessPage'
// export { default as PaymentAddr } from '__payment__/modules/PaymentAddr'
// export { default as PaymentPost } from '__payment__/modules/PaymentPost'